### ISSUE TITLE
Issues appearing multiple times

### ISSUE THREAD

**Issue by mrcnski** [Xion/cargo-contribute#2]
I just ran `cargo contribute` on one of my crates and the same issue appeared several times:

```
[rust-num/num] #341: num_derive for newtypes -- https://github.com/rust-num/num/issues/341
[rust-num/num] #341: num_derive for newtypes -- https://github.com/rust-num/num/issues/341
[rust-num/num] #341: num_derive for newtypes -- https://github.com/rust-num/num/issues/341
```

I haven't looked at the code but could it be considering the same dependency (e.g. `num`) multiple times, if it's a sub-dependency of other dependencies?

In the spirit of this crate, I'd like to tackle this myself when I have the time. :)

**Comment by Xion** [comment]
That's interesting. The program isn't actually looking at indirect dependencies, so it should only have searched in a single repository once.

In theory, there may be a case where two different crates you directly depend on have the same `repository` entry in their manifests. Perhaps this is what's happening? But I don't think anything other than `num` is hosted under that repo.

If you want to tackle this, the main entry point for the issue suggestion logic is [here](https://github.com/Xion/cargo-contribute/blob/ecfc333b4b949e6eb1c17bac87d6978700e5ad53/src/issues/producer.rs#L67). If the problem is reproducible, I recommend running the binary with `-v` to see what repos are actually being searched through.
